### ISSUE TITLE
We should have an option to delete reports

### ISSUE THREAD

**Issue by hugodopradofernandes** [klustair/klustair-frontend#14]
We should have an option to delete reports

**Comment by mms-gianni** [comment]
This is clearly a must have feature. I'm not sure where to add it, since there is currently no list view of all reports.

Since all report data is linked with foreign keys in the Postgres database, it's easy to implement by just deleting one row in the k_report table.

**Comment by mms-gianni** [comment]
It took some time to accomplish but its finally here and will be shipped with version 3.1
