### ISSUE TITLE
Grafana Dashboard from Klustair DB data

### ISSUE THREAD

**Issue by hugodopradofernandes** [klustair/klustair-frontend#20]
I started to build a Grafana Dashboard from Klustair DB data

Link: https://grafana.com/grafana/dashboards/13414
Scrennshot: https://i.imgur.com/w5idjyi.png

Is it an "improvement"? I could not find another way to categorize it, only posting here to let you aware of it :)

It's an additional option to visualize data on the same place as I have all other monitoring metrics. 
Klustair Frontend UI still holds much more details, then the idea is using the dashboard side by side with the Klustair Frontend

**Comment by mms-gianni** [comment]
Holy moly. This is very cool.

**Comment by mms-gianni** [comment]
I keep this issue open until i've added a mention on Readme.md

**Comment by mms-gianni** [comment]
I finally got my Grafana 7. 

It looks like it need some minor changes since I made some changes database in version 0.3.0

Would you mind publish it in a gist (https://gist.github.com/hugodopradofernandes) so i can fork it?

**Comment by hugodopradofernandes** [comment]
Hi, I have been on vacations, I'll return next week. Then I will install the updated klustair version and update also the dashboard, fixing the queries

**Comment by hugodopradofernandes** [comment]
Done, only needed to change 2 table names in 4 widget queries.

https://gist.github.com/hugodopradofernandes/b7c1934f73bdcbc099fc0f39a9f2f327

**Comment by mms-gianni** [comment]
This is awesome. Thank you very much for your contribution.
